---


- name: iptables
  hosts: all

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install iptables
      package:
        name: iptables

    - name: Install ifupdown
      package:
        name: ifupdown

    - name: Flush all
      ansible.builtin.iptables:
        flush: yes

    - name: Firewall rule - allow all loopback traffic
      ansible.builtin.iptables:
        action: append
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Allow related and established connections
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT


    - name: Allow all port 22
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_ports:
          - 22
          - 2222
          - 80
        jump: ACCEPT

    - name: Forward port 2222 to 22
      ansible.builtin.iptables:
        table: nat
        chain: PREROUTING
        in_interface: eth0
        protocol: tcp
        match: tcp
        destination_port: 2222
        jump: REDIRECT
        to_ports: 22


    - name: Allow all outgoing
      ansible.builtin.iptables:
        chain: OUTPUT
        protocol: all
        jump: ACCEPT

    - name: Drop everything
      ansible.builtin.iptables:
        chain: INPUT
        protocol: all
        jump: DROP

    - name: Drop everything forward
      ansible.builtin.iptables:
        chain: FORWARD
        protocol: all
        jump: DROP

    - name: Save IPTables rules
      command: iptables-save --file=/etc/iptables.rules

    - name: Install IPTables pre-up file
      template:
        src: "templates/iptables-pre-up.j2"
        dest: "/etc/network/if-pre-up.d/iptables-pre-up"
        owner: root
        group: root
        mode: 0755

    


