---

- name: loadbalancers
  hosts: lbs 

  tasks:

    - name: Install HAProxy
      package:
        name: haproxy

    - name: Start HAProxy
      service:
        name: haproxy
        state: started
        enabled: yes

    - name: Configure HAProxy
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0664

    - name: Check for errors
      command: "haproxy -c -f /etc/haproxy/haproxy.cfg"
      register: error_check

    - name: Reload HAProxy Enterprise if the check passed
      service:
        name: haproxy
        state: reloaded
      when: error_check is success and not ansible_check_mode
