---

- name: loadbalancers
  hosts: lbs 

  tasks:

    - name: Install HAProxy
      package:
        name: haproxy

    - name: Configure HAProxy
      template:
        src: templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: root
        group: root
        mode: 0664
      notify: Reload HAProxy

    - name: Start HAProxy
      service:
        name: haproxy
        state: started
        enabled: yes

  handlers:
    - name: Reload HAProxy
      service:
        name: haproxy
        state: reloaded
